<a href="https://colab.research.google.com/github/bilnazir/stockmarketprediction/blob/LSTM_Sony/fyp_LSTM_sony.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas-ta

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.1/115.1 kB 2.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pandas-ta: filename=pandas_ta-0.3.14b0-py3-none-any.whl size=218909 sha256=488a900b94cfb370e29dfa8294c45048fc2ddc6bd078c66a4d33607f35dceea8
  Stored in directory: /root/.cache/pip/wheels/69/00/ac/f7fa862c34b0e2ef320175100c233377b4c558944f12474cf0
Successfully built pandas-ta


In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import yfinance as yf
import pandas_ta as ta
data = yf.download(tickers = 'SONY', start = '2012-03-11',end = '2022-07-10')
data.head(10)

[*********************100%%**********************]  1 of 1 completed


Open       High        Low      Close  Adj Close   Volume
Date                                                                      
2012-03-12  20.930000  21.020000  20.780001  20.850000  20.850000   636000
2012-03-13  20.860001  21.150000  20.840000  21.139999  21.139999  2088500
2012-03-14  21.580000  21.730000  21.430000  21.590000  21.590000  1334400
2012-03-15  21.680000  21.830000  21.600000  21.750000  21.750000  1112700
2012-03-16  21.980000  22.049999  21.760000  21.809999  21.809999  1925900
2012-03-19  21.620001  21.700001  21.480000  21.650000  21.650000  1230600
2012-03-20  21.420000  21.440001  21.200001  21.379999  21.379999   965500
2012-03-21  20.700001  20.820000  20.559999  20.719999  20.719999  1541600
2012-03-22  20.670000  20.670000  20.490000  20.549999  20.549999   927100
2012-03-23  20.160000  20.330000  20.010000  20.320000  20.320000  1035000

In [3]:
# Adding indicators
data['RSI']=ta.rsi(data.Close, length=15)
data['EMAF']=ta.ema(data.Close, length=20)
data['EMAM']=ta.ema(data.Close, length=100)
data['EMAS']=ta.ema(data.Close, length=150)

data['Target'] = data['Adj Close']-data.Open
data['Target'] = data['Target'].shift(-1)

data['TargetClass'] = [1 if data.Target[i]>0 else 0 for i in range(len(data))]

data['TargetNextClose'] = data['Adj Close'].shift(-1)

data.dropna(inplace=True)
data.reset_index(inplace = True)
data.drop(['Volume', 'Close', 'Date'], axis=1, inplace=True)

<ipython-input-3-bcaa738bef9c>:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data['TargetClass'] = [1 if data.Target[i]>0 else 0 for i in range(len(data))]


In [4]:
data_set = data.iloc[:, 0:11]
pd.set_option('display.max_columns', None)

data_set.head(20)

Open   High    Low  Adj Close        RSI       EMAF       EMAM  \
0   11.51  11.53  11.44      11.44  40.947514  11.893336  13.241486   
1   11.52  11.59  11.30      11.36  39.822149  11.842542  13.204229   
2   11.63  11.71  11.59      11.69  46.339994  11.828014  13.174244   
3   11.91  12.03  11.90      12.00  51.614637  11.844394  13.150992   
4   12.17  12.27  12.16      12.23  55.121423  11.881118  13.132754   
5   12.35  12.40  12.28      12.35  56.868880  11.925773  13.117254   
6   12.32  12.35  12.06      12.15  53.171795  11.947128  13.098101   
7   12.28  12.37  12.21      12.35  56.221179  11.985497  13.083287   
8   12.10  12.12  11.91      12.09  51.545935  11.995450  13.063618   
9   12.18  12.20  11.99      12.02  50.338428  11.997788  13.042952   
10  11.99  12.03  11.82      11.90  48.261840  11.988475  13.020319   
11  11.76  11.88  11.76      11.85  47.389126  11.975287  12.997145   
12  11.94  11.97  11.71      11.74  45.451752  11.952878  12.972251   
13  11.69  11.97  11.67      11.82  47.135799  11.940223  12.949434   
14  11.68  11.68  11.32      11.33  39.194858  11.882107  12.917366   
15  11.35  11.36  11.08      11.25  38.072857  11.821906  12.884349   
16  11.18  11.23  11.08      11.18  37.077799  11.760772  12.850599   
17  11.29  11.29  11.04      11.18  37.077799  11.705461  12.817518   
18  11.06  11.10  10.87      10.90  33.104845  11.628750  12.779548   
19  10.94  11.00  10.83      10.86  32.570662  11.555536  12.741537   

         EMAS    Target  TargetClass  TargetNextClose  
0   14.298733 -0.160001            0            11.36  
1   14.259810  0.059999            1            11.69  
2   14.225772  0.090000            1            12.00  
3   14.196292  0.059999            1            12.23  
4   14.170248  0.000000            0            12.35  
5   14.146139 -0.170000            0            12.15  
6   14.119700  0.070001            1            12.35  
7   14.096261 -0.010000            0            12.09  
8   14.069688 -0.160000            0            12.02  
9   14.042539 -0.090000            0            11.90  
10  14.014161  0.090000            1            11.85  
11  13.985497 -0.200000            0            11.74  
12  13.955755  0.130000            1            11.82  
13  13.927467 -0.350000            0            11.33  
14  13.893064 -0.100000            0            11.25  
15  13.858056  0.000000            0            11.18  
16  13.822585 -0.110000            0            11.18  
17  13.787584 -0.160001            0            10.90  
18  13.749338 -0.080000            0            10.86  
19  13.711069 -0.120001            0            10.65

In [5]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range=(0,1))
data_set_scaled = sc.fit_transform(data_set)
print(data_set_scaled)

[[0.0154082  0.01467268 0.01574869 ... 0.52534124 0.         0.0145427 ]
 [0.01548887 0.0151564  0.01456965 ... 0.54678376 1.         0.01731674]
 [0.01637625 0.01612383 0.01701196 ... 0.5497078  1.         0.01992266]
 ...
 [0.56502098 0.57489517 0.58514405 ... 0.46686233 0.         0.59431745]
 [0.57671828 0.5754595  0.59280782 ... 0.71929857 1.         0.62104913]
 [0.58147791 0.59674301 0.60729326 ... 0.55555589 1.         0.61323137]]


In [6]:
# multiple feature from data provided to the model
X = []

backcandles = 30
print(data_set_scaled.shape[0])
for j in range(8):#data_set_scaled[0].size):#2 columns are target not X
    X.append([])
    for i in range(backcandles, data_set_scaled.shape[0]):#backcandles+2
        X[j].append(data_set_scaled[i-backcandles:i, j])

#move axis from 0 to position 2
X=np.moveaxis(X, [0], [2])

# Choose -1 for last column, classification else -2...
X, yi =np.array(X), np.array(data_set_scaled[backcandles:,-1])
y=np.reshape(yi,(len(yi),1))
print(X)
print(X.shape)
print(y)
print(y.shape)

2449
[[[1.54081953e-02 1.46726838e-02 1.57486939e-02 ... 1.54805105e-02
   1.63141049e-02 1.94928779e-02]
  [1.54888683e-02 1.51564021e-02 1.45696524e-02 ... 1.50380277e-02
   1.59640198e-02 1.91112409e-02]
  [1.63762486e-02 1.61238310e-02 1.70119631e-02 ... 1.49114709e-02
   1.56822696e-02 1.87775140e-02]
  ...
  [3.38819043e-03 3.06352882e-03 3.53714068e-03 ... 5.75525806e-03
   8.04468459e-03 1.02215927e-02]
  [2.01677965e-03 3.30538413e-03 2.35809914e-03 ... 5.12725790e-03
   7.60901889e-03 9.78873600e-03]
  [2.66214853e-03 1.85423688e-03 2.10544050e-03 ... 4.45950845e-03
   7.15965187e-03 9.34602865e-03]]

 [[1.54888683e-02 1.51564021e-02 1.45696524e-02 ... 1.50380277e-02
   1.59640198e-02 1.91112409e-02]
  [1.63762486e-02 1.61238310e-02 1.70119631e-02 ... 1.49114709e-02
   1.56822696e-02 1.87775140e-02]
  [1.86350397e-02 1.87036415e-02 1.96227048e-02 ... 1.50541594e-02
   1.54637798e-02 1.84884653e-02]
  ...
  [2.01677965e-03 3.30538413e-03 2.35809914e-03 ... 5.12725790e-03
   7.

In [7]:
# split data into train test sets
splitlimit = int(len(X)*0.8)
print(splitlimit)
X_train, X_test = X[:splitlimit], X[splitlimit:]
y_train, y_test = y[:splitlimit], y[splitlimit:]
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(y_train)

1935
(1935, 30, 8)
(484, 30, 8)
(1935, 1)
(484, 1)
[[0.00134499]
 [0.00226967]
 [0.00092468]
 ...
 [0.60221922]
 [0.61987227]
 [0.60205113]]


In [ ]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import Dense
from keras.layers import TimeDistributed
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.metrics import MeanAbsoluteError

import tensorflow as tf
import keras
from keras import optimizers
from keras.callbacks import History
from keras.models import Model
from keras.layers import Dense, Dropout, LSTM, Input, Activation, concatenate
import numpy as np

np.random.seed(10)

lstm_input = Input(shape=(backcandles, 8), name='lstm_input')
inputs = LSTM(150, name='first_layer')(lstm_input)
inputs = Dense(1, name='dense_layer')(inputs)
output = Activation('linear', name='output')(inputs)
model = Model(inputs=lstm_input, outputs=output)
adam = optimizers.Adam()
model.compile(optimizer=adam, loss=MeanSquaredError(), metrics=[MeanAbsoluteError()])
history = model.fit( X_train,
    y_train,
    batch_size=64,
    epochs=128,
    validation_data=(X_test, y_test),
    verbose=1,)

Epoch 1/128
31/31 ━━━━━━━━━━━━━━━━━━━━ 4s 70ms/step - loss: 0.0144 - mean_absolute_error: 0.0792 - val_loss: 0.0066 - val_mean_absolute_error: 0.0689
Epoch 2/128
31/31 ━━━━━━━━━━━━━━━━━━━━ 2s 61ms/step - loss: 3.3038e-04 - mean_absolute_error: 0.0138 - val_loss: 0.0022 - val_mean_absolute_error: 0.0372
Epoch 3/128
31/31 ━━━━━━━━━━━━━━━━━━━━ 3s 62ms/step - loss: 1.8153e-04 - mean_absolute_error: 0.0098 - val_loss: 0.0019 - val_mean_absolute_error: 0.0350
Epoch 4/128
31/31 ━━━━━━━━━━━━━━━━━━━━ 2s 63ms/step - loss: 1.5265e-04 - mean_absolute_error: 0.0090 - val_loss: 0.0018 - val_mean_absolute_error: 0.0343
Epoch 5/128
31/31 ━━━━━━━━━━━━━━━━━━━━ 4s 113ms/step - loss: 1.3656e-04 - mean_absolute_error: 0.0087 - val_loss: 0.0016 - val_mean_absolute_error: 0.0312
Epoch 6/128
31/31 ━━━━━━━━━━━━━━━━━━━━ 2s 65ms/step - loss: 1.2078e-04 - mean_absolute_error: 0.0081 - val_loss: 0.0015 - val_mean_absolute_error: 0.0309
Epoch 7/128
31/31 ━━━━━━━━━━━━━━━━━━━━ 2s 59ms/step - loss: 1.1427e-04 - mean_a

In [9]:
# Convert training history to datafram for viewing and graphing.
hist = pd.DataFrame(history.history)
hist.head()

loss  mean_absolute_error  val_loss  val_mean_absolute_error
0  0.005528             0.046246  0.006561                 0.068869
1  0.000272             0.012359  0.002168                 0.037234
2  0.000169             0.009443  0.001919                 0.034991
3  0.000147             0.008892  0.001840                 0.034318
4  0.000129             0.008363  0.001564                 0.031174